language: c

script: ./.travis-build.sh

# Version for Ubuntu 14.04 Trusty.
sudo: required
dist: trusty
before_install:
  - sudo apt-get update -qq
  # need binutils-dev to get bfd.h
  # need texinfo and texlive for makeinfo program
  - sudo apt-get install -qq binutils-dev texinfo texlive

## Version for container-based infrastructure.
## Commented out because Ubuntu 12.04 Precise is too old and gives spurious test failures.
# addons:
#   apt:
#     packages:
#     # need binutils-dev to get bfd.h
#     - binutils-dev
# # On Travis-CI's Ubuntu 12.04 infrastructure, makeinfo does not take the
# # --split=chapter command-line argument but texi2html does.
# env: TEXI2HTML=texi2html

git:
  depth: 3
