jobs:

- job: ubuntu
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/daikon-ubuntu-jdk8-plus:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./test.sh
    displayName: test.sh

- job: fedora
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/daikon-fedora-jdk8-plus:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./test.sh
    displayName: test.sh

- job: centos
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/daikon-centos-jdk8-plus:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./test.sh
    displayName: test.sh
