jobs:

- job: ubuntu
  pool:
    vmImage: 'ubuntu-16.04'
  container: mdernst/daikon-ubuntu-jdk8-plus:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./test.sh
    displayName: test.sh

## TODO
# - job: fedora_new_docker_container
#   pool:
#     vmImage: 'ubuntu-16.04'
#   container: mdernst/daikon-fedora-jdk8-plus:latest
#   steps:
#   - checkout: self
#     fetchDepth: 25
#   - bash: ./test.sh
#     displayName: test.sh

- job: fedora_old_docker_container
  pool:
    vmImage: 'ubuntu-16.04'
  container: mdernst/fedora-for-daikon-jdkany:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./test.sh
    displayName: test.sh

- job: centos
  pool:
    vmImage: 'ubuntu-16.04'
  container: mdernst/daikon-centos-jdk8-plus:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./test.sh
    displayName: test.sh
