jobs:

# The JDK version doesn't matter, but these Docker images happen to use
# different underlying OS versions.

- job: ubuntu_stable
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/daikon-ubuntu-jdk8-plus:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./test.sh
    displayName: test.sh

- job: ubuntu_rolling
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/daikon-ubuntu-jdk24-plus:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./test.sh
    displayName: test.sh

- job: rocky
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/daikon-rockylinux-jdk8-plus:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./test.sh
    displayName: test.sh
